#
# red82 // software
# Alfonso E. Urdaneta
# alfonso@red82.com
#
CC=g++

OBJECTS = 	Solver.o

CFLAGS=-g -v -Wall -std=c++11

solver	: $(OBJECTS)
	$(CC) $(CFLAGS) -o solver $(OBJECTS)

clean	:
	rm solver $(OBJECTS)
