#
# red82 // software
# Alfonso E. Urdaneta
# alfonso@red82.com
#
CC=g++


SOURCE=rnikg.cc

CFLAGS=-g -v $(SOURCE)
LDFLAGS=$(LIBRARIES) $(FRAMEWORKS)
OUT=-o rnikg

all:
	$(CC)		\
	$(CFLAGS)	\
	$(LDFLAGS)	\
	$(OUT)

clean:
	rm -rf	*.dSYM	rnikg
