#
# red82 // software
# Alfonso E. Urdaneta
# alfonso@red82.com
#
CC=gcc


SOURCE=reverse.c

CFLAGS=-g -v $(SOURCE)
LDFLAGS=$(LIBRARIES) $(FRAMEWORKS)
OUT=-o reverse

all:
	$(CC)		\
	$(CFLAGS)	\
	$(LDFLAGS)	\
	$(OUT)

clean:
	rm -rf	*.dSYM	reverse
