#
# red82 // software
# Alfonso E. Urdaneta
# alfonso@red82.com
#
CC=g++

OBJECTS = 	TextJustification.o

CFLAGS=-g -v -Wall -std=c++11

text_justification : $(OBJECTS)
	$(CC) $(CFLAGS) -o TestJustification $(OBJECTS)

clean	:
	rm text_justification $(OBJECTS)
